apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: gotham-git
  namespace: gotham-kargo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  subscriptions:
      - git:
          repoURL: https://github.com/gotham-demo/gotham-cd.git
          branch: main