apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: gotham-images
  namespace: gotham-kargo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  subscriptions:
      - image:
          repoURL: quay.io/gotham/batman
          tagSelectionStrategy: NewestBuild
      - image:
          repoURL: quay.io/gotham/joker
          tagSelectionStrategy: NewestBuild
      - image:      
          repoURL: quay.io/gotham/robin
          tagSelectionStrategy: NewestBuild
