apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: gotham
  namespace: gotham-kargo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  subscriptions:
      - image:
          repoURL: 'quay.io/gotham/batman'
          updateStrategy: "NewestBuild"
      - image:      
          repoURL: 'quay.io/gotham/robin'
          updateStrategy: "NewestBuild"
      - git:
          repoURL: https://github.com/gotham-demo/gotham-cd.git
          branch: main