apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: gotham
  namespace: gotham-kargo
spec:
  subscriptions:
    repos:
      images:
      - repoURL: quay.io/gotham/batman
        updateStrategy: Latest
      - repoURL: quay.io/gotham/robin
        updateStrategy: Latest
      - repoURL: quay.io/gotham/joker
        updateStrategy: Latest
      git:
      - repoURL: https://github.com/gotham-demo/gotham-cd.git
        branch: main