kind: ServiceAccount
apiVersion: v1
metadata:
  name: pipeline
  namespace: demo-develop
secrets:
  - name: pipeline-dockercfg-szpkd
  - name: gh-token
  - name: gitea-token
  - name: sparky-cicd
imagePullSecrets:
  - name: pipeline-dockercfg-szpkd
  - name: sparky-cicd
