apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: riddler-image
  namespace: gotham-kargo
  annotations:
    kargo.akuity.io/color: green
spec:
  subscriptions:
    repos:
      images:
      - repoURL: quay.io/gotham/riddler
        updateStrategy: Latest
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/gotham-demo/gotham-cd.git #https://gitea-http.gitea.svc/gotham/gotham-cd.git
      writeBranch: riddler # Writing to stage-specific branch prevents the formation of a loop
      helm:
        images:
        - image: quay.io/gotham/riddler
          valuesFilePath: Application/gotham-demo/develop/values-riddler.yaml
          key: image.tag # Update this key to reference the new image version
          value: 'Tag'
